name: Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test-linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        VSCODE_VERSION: ['latest', 'minimum']
        experimental: [false]
        include:
          - VSCODE_VERSION: 'insiders'
            experimental: true
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Webpack # test does not use it, but we are testing the webpack creation
        run: |
          npm run webpack
          ls -all out/dist

      - name: Test
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3
          npm test
        env:
          C2_DEBUG: true
          DISPLAY: ':99.0'

  test-windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        VSCODE_VERSION: ['latest', 'minimum']
        experimental: [false]
        include:
          - VSCODE_VERSION: 'insiders'
            experimental: true
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Test
        run: npm test
        env:
          C2_DEBUG: true

  test-mac:
    name: MacOS
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        VSCODE_VERSION: ['latest', 'minimum']
        experimental: [false]
        include:
          - VSCODE_VERSION: 'insiders'
            experimental: true
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Test
        run: npm test
